### PR TITLE
Jb ras mr1

### PR DESCRIPTION
**Pull request by pbeeler**
I fixed the merge conflicts previously was because my frameworks has theme support but it should work fine now for rasbeanjelly after the png images.  You could probably just backup the png images and then copy them over after the merge and re-push with new png images.  Cheers.

### CODE REVIEW

**Comment by pbeeler** [comment]
Whatever

**Comment by rascarlo** [comment]
https://github.com/rascarlo/platform_frameworks_base/commit/80d0764f363b3bb270062b6380a39f6ff3ab5c7f

**Comment by pbeeler** [comment]
https://github.com/rascarlo/platform_packages_apps_settings/commit/c9d9f3e92cff823107f975bd5bbf90fc9250cdc8
Your not the author of this patch @Danesh is.  Just because you changed some png's around that makes you the author?  You could just make all the png's a separate commit.

**Comment by pbeeler** [comment]
Original author and patch is here and it's been signed off by me also.
https://github.com/pbeeler/android_packages_apps_Settings/commit/fca257f5c75a8a94a4ba9b64a1836793a53755e7

**Comment by rascarlo** [comment]
i don't get it. what is wrong @pbeeler ?
the whole world knows those commits belong to CM. i like to edit my code manually.

**Comment by rascarlo** [comment]
@pbeeler you are done like that? i mean, don't care to explain or what?

**Comment by pbeeler** [comment]
@rascarlo I don't get it either.  You could at least put in the commit messages link to original patch and/or author so other people on github know.  How are they to know without this information?  How does the whole world know?

git commit --amend after cherry-pick the patch.  Is it because you don't like to fix merge conflicts and such things?  I'm trying to understand this.

**Comment by rascarlo** [comment]
there are few things i like to code by myself, watching what the others did. it is a way to have fun and challenge myself. if you take a look at my github history, which i am sure you did, you will notice there are some edits that i like to do in this way, but you will also see a lot of commits with the original authors. i estimate 95 over 100%.
you mean i should do like this? https://github.com/rascarlo/platform_frameworks_base/commit/b41597536f4df9f9062338fbbb70a82e6b1b8047

**Pull request closed without merging**
