### PR TITLE
Jb ras mr1

### PR DESCRIPTION
**Pull request by pbeeler**
Happy New Year.  You have to redo png colors though :)

### CODE REVIEW

**Comment by pbeeler** [comment]
Looks like a problem with packages/SystemUI/src/com/android/systemui/statusbar/phone/PhoneStatusBar.java for some reason.  I didn't have a merge conflict on my other frameworks repo.  Anyways get passed that and your golden.

**Comment by rascarlo** [comment]
i will take a look.
not sure i want to add this thing to my build.
thank you

**Comment by rascarlo** [comment]
and happy new year paul!

**Comment by pbeeler** [comment]
Really you don't want navigation bar customization working for grouper?  Or the height change?

**Comment by rascarlo** [comment]
the height customization.
i will now build with your code and check it out for few days
thank you paul

**Comment by pbeeler** [comment]
Working fine here for me no issues.  If you have any suggestions on how to improve it or any concerns with it let me know.

**Pull request merged**
